export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_USER_THEME = "SET_USER_THEME";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const DECREASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY";
export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";
export const SAVE_ORDER = "SAVE_ORDER";